Add s2t t2s configs
ondewo/ondewo-vtsi-api pull request #11
Opened 2021-12-03 10:34 UTC by MohamedYaman

2021-12-03 12:02 UTC, gaborod16 requested changes
As you suggested @MohamedYaman make minimal changes work first and then do the massive ones in a different branch :dagger:

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/call_log.proto
> +package ondewo.vtsi;
:boom:

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/call_log.proto
> +    rpc ActivateSaveCallLogs (google.protobuf.Empty) returns (SaveCallLogsResponse) ;
This endpoint should be deprecated in the future since the `CallLogs` should always be saved by default (taks: https://ondewo.atlassian.net/browse/OND233-287)

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/call_log.proto
>    double end_time = 3;
The `VoipLog` message does not contain any *logs*.
Either the logs should be added or the message should be renamed to `VoipCallStatus`.

I do not think having the logs passed on a gRPC response would be useful tho.

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/call_log.proto
>  service VoipCallLogs {
This service makes no sense to be isolated.
Should be merged with all VoipCall related endpoints

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  rpc StopCall (StopCallRequest) returns (StopCallResponse);
Add comment stating that this endpoint stops both *Inbound* and *Outbound* calls.

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  DateTime scheduled_time = 2;
Better use the `Timestamp` proto message like so:

// the time the operation was submitted.
google.protobuf.Timestamp create_time = 4;

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  rpc GetStatus (GetVoipStatusRequest) returns (VoipStatus);
These endpoints should be pointed as deprecated, also they have a name collision with the ones in `call_log.proto` so probably should be renamed as well.

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  rpc StartScheduledCaller (StartScheduledCallerRequest) returns (StartScheduledCallerResponse);
You can use the endpoint `StartMultipleScheduledCallers` and if you need to start only one, well, you specify only one.

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  rpc StartScheduledCaller (StartScheduledCallerRequest) returns (StartScheduledCallerResponse);
Same for StartCall and StartListener

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +message BaseConfig{
wouldn't be this: `BaseServiceConfig` name?

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  // Base config
NLU is missing credential information:

Credentials or the Auth Token, check the NLUClient for more details

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +message ServicesConfigs{
Better name it `CommonServicesConfigs`

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +message ServicesConfigs{
It is common for both inbound and outbound / listener and caller

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  bool success = 2;
In case of errors it should include the error message

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +message DateTime {
use Timestamp instead

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
>    string call_id = 1;
This call_id is optional and will be generated if not provided

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  ServicesConfigs servies_configs = 2;
typo

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  ServicesConfigs servies_configs = 2;
typo

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
>      string sip_id = 2;
This is actually the `asterisk_account_id`

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
>  service VoipSessions {
Add endpoints to retrieve all "AsteriskAccountIDs" and "CallIDs".

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
>  service VoipSessions {
Also and endpoint to get a Call ID of an active call from an AsteriskAccount (if useful)

2021-12-03 12:02 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
>    string last_log = 2;
unclear what this field is.

Should be all logs I guess

2021-12-06 09:39 UTC, gaborod16 requested changes
Second review iteration

2021-12-06 09:39 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +enum VoipCallStatusView {
Comment on what is the difference between each view

2021-12-06 09:39 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  string call_id = 1;
The information of the call should be wrapped in a message for cohesion.
Should include:

- Call ID
- SIP Account
- Container Name
- Start time
- End time
- Status (current status)
- Display Name (or description) (can be filled with the NLU project name if not provided)
- Type of call (Inbound or outbound)
- Phone number

2021-12-06 09:39 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  string call_id = 1;
Could be named "VoipCallInfo"

2021-12-06 09:39 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +message GetAllVoipCallStatusesResponse{
Should be `ListVoipCallInfo` and allow:

- Sorting
- Pagination
- Filtering

2021-12-06 09:39 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  rpc GetSipAccounts (google.protobuf.Empty) returns (GetSipAccountsResponse);
Rename to VoipAccounts

2021-12-06 09:39 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  rpc GetCallIDs (google.protobuf.Empty) returns (GetCallIDsResponse);
The `GetAllVoipCallStasuses` is much better

2021-12-06 09:39 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +  rpc GetVoipCallStatus (GetVoipCallStatusRequest) returns (GetVoipCallStatusResponse);
GetVoipCallInfo

and 

ListVoipCallInfo

2021-12-06 09:39 UTC, gaborod16 commented on ondewo/vtsi/voip.proto
> +    string auth_token = 3;
```
authentication {
    credentials
    token
}
```

2022-08-11 12:49 UTC, MohamedYaman commented
Outdated

2022-08-11 12:49 UTC, closed without merging